"""empty message

Revision ID: 0e8a381f6a8c
Revises: a0d172409773
Create Date: 2019-08-05 14:21:39.562966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e8a381f6a8c'
down_revision = 'a0d172409773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('skype_id', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'skype_id')
    # ### end Alembic commands ###
