"""empty message

Revision ID: 212981e0a1ab
Revises: 0e8a381f6a8c
Create Date: 2019-08-06 14:49:45.263194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212981e0a1ab'
down_revision = '0e8a381f6a8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    # ### end Alembic commands ###
