"""empty message

Revision ID: 320dadd1953d
Revises: 212981e0a1ab
Create Date: 2019-08-07 18:25:56.251784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '320dadd1953d'
down_revision = '212981e0a1ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohort',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cohort_active'), 'cohort', ['active'], unique=False)
    op.create_index(op.f('ix_cohort_name'), 'cohort', ['name'], unique=False)
    op.create_table('cohort_association',
    sa.Column('cohort', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cohort'], ['cohort.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cohort_association')
    op.drop_index(op.f('ix_cohort_name'), table_name='cohort')
    op.drop_index(op.f('ix_cohort_active'), table_name='cohort')
    op.drop_table('cohort')
    # ### end Alembic commands ###
