"""empty message

Revision ID: 42d6ad924932
Revises: c7cfb0c554a0
Create Date: 2019-09-02 17:11:40.132325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42d6ad924932'
down_revision = 'c7cfb0c554a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('invisible', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_invisible'), 'user', ['invisible'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_invisible'), table_name='user')
    op.drop_column('user', 'invisible')
    # ### end Alembic commands ###
