"""empty message

Revision ID: 550221863c28
Revises: 320dadd1953d
Create Date: 2019-08-07 18:43:22.221576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550221863c28'
down_revision = '320dadd1953d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cohort_id'), 'cohort', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cohort_id'), table_name='cohort')
    # ### end Alembic commands ###
