"""empty message

Revision ID: 8260c6171fa0
Revises: 3597585bf2df
Create Date: 2019-08-15 15:52:57.252123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8260c6171fa0'
down_revision = '3597585bf2df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_vm_name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user__vm_name'), 'user', ['_vm_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user__vm_name'), table_name='user')
    op.drop_column('user', '_vm_name')
    # ### end Alembic commands ###
