"""empty message

Revision ID: a0d16dbf2731
Revises: 42d6ad924932
Create Date: 2019-09-02 18:39:35.332101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0d16dbf2731'
down_revision = '42d6ad924932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solution', sa.Column('description', sa.String(length=4096), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solution', 'description')
    # ### end Alembic commands ###
