"""empty message

Revision ID: b3fbc460bbd4
Revises: ecd469ec2f4f
Create Date: 2019-08-17 13:54:11.030704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3fbc460bbd4'
down_revision = 'ecd469ec2f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('solution_file', 'path')
    # ### end Alembic commands ###

    with op.batch_alter_table('solution_file') as batch_op:
        batch_op.drop_column('path')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solution_file', sa.Column('path', sa.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###
