"""empty message

Revision ID: c7cfb0c554a0
Revises: b3fbc460bbd4
Create Date: 2019-08-21 14:10:58.102382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7cfb0c554a0'
down_revision = 'b3fbc460bbd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('worm_password', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'worm_password')
    # ### end Alembic commands ###
