"""empty message

Revision ID: d0c461434456
Revises: a0d16dbf2731
Create Date: 2019-09-04 15:43:59.993170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c461434456'
down_revision = 'a0d16dbf2731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lync_link', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lync_link')
    # ### end Alembic commands ###
