"""empty message

Revision ID: ecd469ec2f4f
Revises: 76e3d2749178
Create Date: 2019-08-16 20:36:15.185432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecd469ec2f4f'
down_revision = '76e3d2749178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('cohort_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohort.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solution_id'), 'solution', ['id'], unique=False)
    op.create_index(op.f('ix_solution_name'), 'solution', ['name'], unique=False)
    op.create_table('solution_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('path', sa.String(length=256), nullable=True),
    sa.Column('solution_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['solution_id'], ['solution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solution_file_id'), 'solution_file', ['id'], unique=False)
    op.create_index(op.f('ix_solution_file_name'), 'solution_file', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solution_file_name'), table_name='solution_file')
    op.drop_index(op.f('ix_solution_file_id'), table_name='solution_file')
    op.drop_table('solution_file')
    op.drop_index(op.f('ix_solution_name'), table_name='solution')
    op.drop_index(op.f('ix_solution_id'), table_name='solution')
    op.drop_table('solution')
    # ### end Alembic commands ###
